server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        detector:
          enabled: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: off

management:
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        hikaricp.connections.acquire: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      show-details: always
