server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  jpa:
    show-sql: false

management:
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        hikaricp.connections.acquire: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      show-details: always
